---
version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-type: development
      - dependency-name: aws-sdk
        update-types: [version-update:semver-patch]
