name: 'RPM specs matrix generator'
description: 'Generate job matrix for all RPM specs in the project'
inputs:
  paths:
    description: 'Paths where to look for RPM specs'
    required: false
    default: '.'
  recursive:
    description: 'Search recursively'
    required: false
    default: 'true'
  bundle:
    description: 'Bundle specs in build dependency groups'
    required: false
    default: 'true'
  force:
    description: 'Ignore SimpleDB metadata'
    required: false
    default: 'false'
  sdb-domain:
    description: 'AWS SimpleDB domain'
    required: false
    default: 'packages'
outputs:
  matrix:
    description: 'Job matrix'
runs:
  using: 'node12'
  main: 'dist/index.js'
